name: release
# description:

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
  # push:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt install -y curl xz-utils make git wget zip 
          echo "dir:$PWD"
          echo "${{ github.action_path }}"
          latest_version=$(wget --no-check-certificate -qO- "https://api.github.com/repos/stunnel/static-curl/releases" | grep "tag_name" | grep -oE "[0-9.]*" | head -1)
          download_link="https://github.com/stunnel/static-curl/releases/download/${latest_version}/curl-linux-aarch64-${latest_version}.tar.xz"
          echo ${download_link}
          wget -O curl.tar.xz ${download_link}
          tar -xJf curl.tar.xz -C $PWD/bin
          mkdir $PWD/toolchain 
          wget -O arm64.tar.xz "https://mirrors.tuna.tsinghua.edu.cn/armbian-releases/_toolchain/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu.tar.xz" 
          xz -d arm64.tar.xz
          tar -xvf arm64.tar -C $PWD/toolchain 
          rm -f arm64.tar curl.tar.xz
          
      - name: Build Zerotier
        run: |
          export PATH="$PWD/toolchain/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu/bin/:${PATH}"
          zerotier_latest_version=$(wget --no-check-certificate -qO- "https://api.github.com/repos/zerotier/ZeroTierOne/releases" | grep "tag_name" | grep -oE "[0-9.]*" | head -1)
          echo "VERSION=$zerotier_latest_version" >> $GITHUB_ENV
          git clone https:///github.com/zerotier/ZeroTierOne.git --depth=1 -b ${zerotier_latest_version}
          cd ZeroTierOne
          make ZT_STATIC=1 ZT_DEBUG=0 ZT_SSO_SUPPORTED=0 CC=aarch64-none-linux-gnu-gcc CXX=aarch64-none-linux-gnu-g++ LDFLAGS="-s"
          cp -rf zerotier-one ../
          ls

      - name: Build UI
        run: |
          cd ui-src
          npm install
          npm run build
          mv dist/* ../webroot/

      - name: Generate module
        run: |
          rm -rf ZeroTierOne toolchain ui-src
          ls -la
          zip -r -o -X -ll ZeroTierForKSU.zip ./ -x '.git/*' -x '.gitignore' -x '.github/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZeroTierForKSU
          path: ./ZeroTierForKSU.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.VERSION }}
          name: ZeroTierForKSU-${{ env.VERSION }}
          files: ZeroTierForKSU.zip
